name: Infection
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  infection:
    name: Infection with PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }} dependencies | EdgeDB ${{ matrix.edgedb-version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['7.4', '8.0']
        composer-dependencies: ['highest', 'lowest']
        edgedb-version: ['stable', 'nightly']

    services:
      edgedb:
        image: edgedb/edgedb
        env:
          EDGEDB_USER: 'edgedb'
          EDGEDB_PASSWORD: 'edgedb'
          EDGEDB_DATABASE: 'edgedb'
          VERSION: ${{ matrix.edgedb-version }}
        volumes:
          - dbschema:/dbschema
        ports:
          - 5656:5656
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Edgedb CLI
        uses: edgedb/setup-edgedb@v1
        with:
          cli-version: ${{ matrix.edgedb-version }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, xdebug
          coverage: xdebug
        env:
          update: true

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.composer-dependencies }}
          composer-options: "--prefer-stable"

      - name: Run Infection
        run: php vendor/bin/infection --no-progress --min-covered-msi=100 --min-msi=100 --show-mutations --threads=4
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
          EDGEDB_SERVER: 'edgedb:5656'
